import type { Metadata } from "next";
import { site } from "@/content/site";

const SHARED_OG_IMAGE = "/opengraph-image"; // generated by src/app/opengraph-image.tsx

/**
 * Per-page metadata with canonical URL, Open Graph and Twitter cards.
 *
 * A page that sets its own `openGraph` replaces (does not merge with) the
 * layout's, and drops the image inherited from the root opengraph-image file.
 * So this helper restates title/description AND attaches the shared share image.
 * Pass `image: false` on routes that have their own opengraph-image file
 * (e.g. case studies) so that file is used instead.
 *
 * Relative URLs resolve against metadataBase. Omit `title` for the home page,
 * which uses the full brand title.
 */
export function pageMetadata({
  title,
  description,
  path,
  image,
}: {
  title?: string;
  description: string;
  path: string;
  image?: false;
}): Metadata {
  const fullTitle = title ? `${title} — ${site.name}` : site.title;
  // Omit the keys entirely (rather than passing undefined) so a segment's own
  // opengraph-image file isn't suppressed.
  const images =
    image === false ? {} : { images: [{ url: SHARED_OG_IMAGE, width: 1200, height: 630, alt: site.title }] };

  return {
    title: title ? title : { absolute: site.title },
    description,
    alternates: { canonical: path },
    openGraph: { type: "website", siteName: site.name, locale: "en_US", title: fullTitle, description, url: path, ...images },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      ...(images.images && { images: images.images.map((i) => i.url) }),
    },
  };
}
